kind: Service
apiVersion: v1
metadata:
  name:  voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
  - port:  80
    targetPort:  80
    nodePort: 30004